#!/bin/bash

## Description: Installs medium dataset
## Usage: medium
## Example: "ddev medium"
## ProjectTypes: magento2
## ExecRaw: true

ddev import-db --file=db.medium.sql.gz
ddev magento setup:db-schema:upgrade
ddev magento app:config:import
ddev magento index:reset catalogsearch_fulltext
ddev magento index:reindex catalogsearch_fulltext
