#!/bin/bash
#ddev-generated

## Description: Manage parts of rabbitmq
## Usage: rabbitmqadmin [options] subcommand
## Example: ddev rabbitmqadmin --help

rabbitmqadmin -u "$RABBITMQ_DEFAULT_USER" -p "$RABBITMQ_DEFAULT_PASS" $@
