version: "3.5"

x-volumes: &volumes
  - ${WARDEN_SSL_DIR}/rootca/certs:/etc/ssl/warden-rootca-cert:ro
  - ${WARDEN_COMPOSER_DIR}:/home/www-data/.composer:cached
  - .${WARDEN_WEB_ROOT:-}/:/var/www/html:cached

x-extra_hosts: &extra_hosts
  - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
  - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}

services:
  nginx:
    image: ${WARDEN_IMAGE_REPOSITORY}/nginx:${NGINX_VERSION:-1.16}-training
    build: ./.warden/docker/nginx
    environment:
      - TIDEWAYS_APIKEY

  tideways-daemon:
    build:
      context: ./.warden/docker/tideways-daemon

  varnish:
    volumes:
      - ./.warden/docker/varnish/default.vcl:/etc/varnish/default.vcl.template

  php-tideways:
    hostname: "${WARDEN_ENV_NAME}-php-tideways"
    image: ${WARDEN_IMAGE_REPOSITORY}/php-fpm${WARDEN_SVC_PHP_IMAGE_SUFFIX:-}:${PHP_VERSION:-7.4}${WARDEN_SVC_PHP_VARIANT:-}-tideways
    build:
      context: ./.warden/docker/tideways
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - TIDEWAYS_APIKEY
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-12}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - ${SSH_AUTH_SOCK:-/dev/null}:/run/host-services/ssh-auth.sock
    volumes: *volumes
    extra_hosts: *extra_hosts
    depends_on:
      - php-fpm
